### ISSUE TITLE
[ui] Currency symbols colliding with amounts

### ISSUE THREAD

**Issue by boborchard** [balancemymoney/balance-open#101]
## Screenshot

![balance-open-currency](https://user-images.githubusercontent.com/1667106/29723131-74d581f8-8991-11e7-890b-2cc0a0444535.png)

## Details

*OS:* macOS Sierra 10.12.6
*Balance Version:* 0.9.3

**Comment by wolffan** [comment]
Hello @boborchard first thank so much for your issue submission.
Second we have detected this issue and fixed it, basically removing the crypto simbols (but) ->

Unfortunately the solution didn't take into consideration existing users that had already stored currency symbols.
Quick way of fixing this will be to log out and log in again.
But in case you don't want to do that I'll look into this in order to sort the issue
cc @einsteinx2 the solution currency didn't take into account stored currencies, I'll take a look.

**Comment by boborchard** [comment]
@wolffan I just disconnected and re-authorized my CoinBase account and the issue persisted. Happy to wait for a full fix 👍

**Comment by einsteinx2** [comment]
@wolffan @boborchard Just double checked and it looks like the fix to remove those currency symbols is not in version 0.9.3. It will be in the next update--which should be out this week including Poloniex and GDAX support--and you will not need to do anything other than upgrade to see the fix.
