### ISSUE TITLE
Issues with Ethplorer

### ISSUE THREAD

**Issue by einsteinx2** [balancemymoney/balance-open#203]
From Tom K:

Balance from ETH wallet does show up, but the fiat conversions are off (alt tokens have wrong values, ETH value seems to be zero?). Also a random token CNX shows up.

**Comment by wolffan** [comment]
good point. So for tokens not listed on exchanges usually the value in $ is 0 (they don't have a price, but since they don't show on exchanges I'd say imact is low)
For ETH true that we don't have a rate coming from ethplorer, I'll see if I can just set the alt currency as ETH and the converter just transforms it to whatever

**Comment by wolffan** [comment]
Sorted, this was both an oversight from my part and the fact that ethplore doesn't give a rate for the eth tokens stored
<img width="395" alt="screen shot 2017-10-30 at 12 53 13" src="https://user-images.githubusercontent.com/1092080/32169562-58150142-bd71-11e7-8753-846404530f5b.png">

**Comment by wolffan** [comment]
fixed by. https://github.com/balancemymoney/balance-open/pull/212
