### ISSUE TITLE
Add more analytics + tool for managing all analytics code.

### ISSUE THREAD

**Issue by wolffan** [balancemymoney/balance-open#269]

**Comment by wolffan** [comment]
➤ Raimon Lapuente commented:

@benbaron7 any reason why we are not installing our https://www.hockeyapp.net/help/sdk/ios/5.0.0/installation--setup.html with carthage?

**Comment by wolffan** [comment]
➤ Raimon Lapuente commented:

Also @benbaron7 if we are planning to run our own analytics we should enable hockey only for crashes:

Crash-only extension
carthage build --platform iOS --configuration ReleaseCrashOnlyExtension HockeySDK-iOS

**Comment by einsteinx2** [comment]
Does Carthage support installing hockeyapp for macOS? Maybe that's why we're not using it. I'm not sure.

And agreed, HockeyApp would be great for crashes (I like their interface) and then using Countly for analytics. Though I think Countly also supports crash logging, so maybe we should just do everything there.
