### ISSUE TITLE
Fix Locksmith so it can take in a security level on init (or property). It's causing crashes on iOS and causing background refresh to not work

### ISSUE THREAD

**Issue by wolffan** [balancemymoney/balance-open#277]

**Comment by wolffan** [comment]
➤ Raimon Lapuente commented:

what is the problem with access level? 
just to make sure I understand the problem
3 top libs:
https://github.com/kishikawakatsumi/KeychainAccess
Locksmith
https://github.com/evgenyneu/keychain-swift

**Comment by einsteinx2** [comment]
Basically right now the access level does not allow background access. This is causing an inexplicable crash on launch (the crash makes no sense but must be because of the access level as the cause is that it's sometimes not reading the keychain value) and also causes all background app refreshing to fail.

We are using the default access level, but we need to be using kSecAttrAccessibleAfterFirstUnlock. Locksmith seems to have an enum for this, but the only properties I could see using it were get only. So it wasn't clear that Locksmith allowed setting it. If we can just figure out how to set it with Locksmith that would be much easier than replacing the library. I may have just missed something obvious.

**Comment by einsteinx2** [comment]
Actually I think modifying Locksmith will me much easier. They already have an enum for security level, we just need a way to set it.

**Comment by einsteinx2** [comment]
The more I look at it, I think we should pick a different library actually. Locksmith is a dead project, it's over-engineered, and seems to be failing in weird ways without providing good error feedback. I'm looking for a better keychain wrapper now and will test to make sure it can still read the old keychain entries.

**Comment by einsteinx2** [comment]
Wrote a suuuuper simple KeychainWrapper class (about 60 lines) to replace the Locksmith library. Even wrote tests :)

Also I changed the app launch logic so that it will send a feedback email and displays an alert to the user about the issue if it can't read the db password instead of just crashing on launch.
