### ISSUE TITLE
Create countly self hosted analytics for experimentation

### ISSUE THREAD

**Issue by wolffan** [balancemymoney/balance-open#283]
- [x] sdk installed
- [x] experiment with no self hosted
- [x] self hosted

**Comment by einsteinx2** [comment]
I'm getting the contract signed and back to them today so hopefully we get the download link today or tomorrow for the enterprise version.

**Comment by wolffan** [comment]
Well @einsteinx2 in all honesty we could use hockey for test users as well (for auto updating them, at least on iOS, not sure on mac)

**Comment by einsteinx2** [comment]
For test users on iOS it's _much_ better to use TestFlight (as we already do) because we can support many more beta testers. HockeyApp is limited to how many devices we can have on our developer account, which is only 100 unique devices per year. Those should be reserved for internal test devices, etc.

Closing this ticket as it appears to be complete.
