### ISSUE TITLE
App does not Launch at Login

### ISSUE THREAD

**Issue by ricburton** [balancemymoney/balance-open#487]
**Is this a feature request or bug report?** Bug

**What is the current behavior?** App does not Launch at Login. Checkbo is checked.

**If the current behavior is a bug, please provide the steps to reproduce starting from "launch Balance". If possible, please include a screenshot or a video.**

Restart computer
App does not launch.

**What is the expected behavior?**
App should launch

**Which version of Balance is affected by this issue? Did this work in previous versions of Balance?**
0.9.9

**Comment by einsteinx2** [comment]
That is a very old version...

**Comment by einsteinx2** [comment]
Are you running from Xcode or using the release builds? Also are you running from /Applications? If you aren't running from /Applications it will not work (macOS limitation), and not sure if it will work when using a debug build from Xcode.

**Comment by einsteinx2** [comment]
Also sometimes just having other builds laying around can cause issues. Testing it on my machine now.

**Comment by einsteinx2** [comment]
Didn't work for me or you. Worked for Kristina. We should get some feedback from friends and see if it's working for them. It may only be devs that it doesn't work for. I've found that the helper app frequently finds the incorrect location of the main binary (like it'll find some random path in your xcode build cache instead of in /Applications even though it should obviously look there first) and then fails to run. I'll see if I can add some logging to debug on my machine, but it may very well not affect actual users.

**Comment by einsteinx2** [comment]
This appears to only affect developers. The functionality itself is correct, and from looking into this issue a while back, it's a macOS bug when you have different versions of the app on your machine. Not sure we can actually fix this, and it works for end users, so closing for now.
