### ISSUE TITLE
Coinbase reconnect card has error message

### ISSUE THREAD

**Issue by cjdowner** [balancemymoney/balance-open#518]
Got this a few times. It's quite annoyingly tall. I think it either needs copy with more information (don't know what error codes Coinbase provides), or just make it really short.

<img width="397" alt="screen shot 2018-01-27 at 12 37 51" src="https://user-images.githubusercontent.com/2099705/35472012-fb982690-035e-11e8-9aaf-4445bf07e885.png">

I'm wondering how this can be tied to the Coinbase card itself, or even appear as a card in the list of your accounts. It feels a bit like a cheap UIAlertView which to me makes the thing feel webby (sorry!)

**Comment by einsteinx2** [comment]
This hasn't been skinned yet, that's why it looks so bad. Here's Christian's design for it for 1.0:

![uploads/af4166aa-b4cc-47e2-86ff-ba6da2ec428a/iPhone X Copy 11.jpeg](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Faf4166aa-b4cc-47e2-86ff-ba6da2ec428a%2FiPhone+X+Copy+11.jpeg)

For now it's designed to work the same as the macOS app, but in the future we can certainly improve it to integrate with the cards or something else.

Closing this as we have another issue to skin this that I created before I saw this one.
