### ISSUE TITLE
[Bug] Adding the same account creates multiple account instances in the app

### ISSUE THREAD

**Issue by pacient** [balancemymoney/balance-open#64]
**Problem Description**
When you add a new account with Coinbase the app syncs that Account with Balance and when you keep repeating "Add new account" with the same Coinbase account the app creates more Coinbase account instances of an account that already exists.

**Suggestion For Solution**
I have not really researched how you get all the information from the Coinbase account, however, if you could get an account ID from there and sync that with the account in Balance you could prevent creating another instance of that account if it already exists in the system.

Here is a screenshot of the multiple accounts (same Coinbase account)
![screen shot 2017-07-19 at 14 18 35](https://user-images.githubusercontent.com/19490170/28368693-2bad01e8-6c8d-11e7-91dc-9e17fc83ad13.png)

**Comment by ricburton** [comment]
Not good at all! Thanks for the report Vasil.

**Comment by ricburton** [comment]
Email me privately with your Coinbase email so I can send you crypto.

**Comment by einsteinx2** [comment]
Unfortunately this is not fixable due to their API. We do not have access to account id or anything else identifying the user, likely for security reasons. All we get is an access token which is different for even the same account.

https://developers.coinbase.com/docs/wallet/coinbase-connect/reference
