### ISSUE TITLE
[Idea] Support for Bittrex

### ISSUE THREAD

**Issue by ricburton** [balancemymoney/balance-open#66]
Bittrex is an increasingly popular exchange. They have an API. It would be great to investigate what they are doing.

https://bittrex.com/home/api

**Comment by stefek99** [comment]
I feel so stupid for stating the obvious: https://twitter.com/stefek99/status/892119697109520384

Here: https://commiteth.com/

Not only you'll get the code done, but also reputation and credibility in the crypto space.

**Comment by einsteinx2** [comment]
Notes on implementation:
- Start with authentication (it should be similar to Poloniex)
- Once successfully authenticating, add account and transaction parsing (similar to the other exchanges)
- Feel free to architect the code differently than we have done, as one of our tasks soon is to refactor all of the exchange API code to be consistent so that new APIs can be easily added
- Write unit tests where it makes sense

**Comment by naranjo074** [comment]
This pr add the interface with bittrex, https://github.com/balancemymoney/balance-open/pull/391. Please feel free to comment, any suggestion would be apreciated.

**Comment by einsteinx2** [comment]
I'll get this reviewed and merged this week.

**Comment by einsteinx2** [comment]
This is merged in but note that this is only one part of the task. Creating 2 more issues now.
