### ISSUE TITLE
[Request] Support for Kraken exchange

### ISSUE THREAD

**Issue by Madril** [balancemymoney/balance-open#96]
Support for Kraken exchange

**Comment by ricburton** [comment]
After chatting to the community at the Breaking Bitcoin conference, I think we should prioritise this over other exchanges. 

Kraken have made efforts to cryptographically prove that they store all of the funds. Although this is not 100% proof they are making enough effort to impress Wizsecurity, who was responsible for tracking down the Mt. Gox hack.

**Comment by einsteinx2** [comment]
@ricburton Red has just finished Bitfinex support and will be working on this next. Should be done this week I think.

**Comment by cassiusgray** [comment]
I think this is a great idea Richard. Kraken are rock solid in my view and have good customer service too.

**Comment by reddavis** [comment]
Kraken support has been implemented in the `feature/kraken` branch.

![screen shot 2017-09-19 at 20 41 51](https://user-images.githubusercontent.com/3002/30612017-2a96fe0c-9d7b-11e7-988c-392400f8655d.png)

Couple of things to note:

### Not much data

When fetching account balances we only get the following:

```
{
    "error": [
    
    ],
    "result": {
        "XLTC": "0.0769700000",
        "XBTC": "200.01289712"
    }
}
```

### Super Weird Currency Codes

Not sure if this is some kind of standard(?) but as you can see above Kraken seems to pad currency codes to 4 characters by prepending X (and apparently also Z according to reddit) to them. 

As things are now, I don't think this effects us, but for things like currency conversions or transferring with ShapeShift this will be an issue. We'd need to write something that can turn these padded codes to the actual currency codes. 

I need to do some research to find out whether its a standard that has rules we can use to parse them.

Links:
- https://www.reddit.com/r/Bitcoin/comments/20ff0x/one_downside_of_kraken_is_how_the_currency_pairs/
- https://github.com/CliffS/kraken-exchange/blob/master/README.md

**Comment by Madril** [comment]
Since this disparity is not restricted to Kraken, with the inclusion of new
Exchanges there should be a way to translate values from one system to
another.

**Comment by einsteinx2** [comment]
@Madril we're working on exactly that!

As I'm working on the currency conversion stuff (backend and frontend), I'll chime in here. In this case, we should be stripping the X and Z's as we pull data from Kraken an store it since they're so consistent about it, that way we standardize at the Balance data model level. 

In the case of Kraken, their ticker price API that we use on the backend also calls BTC as XBT instead as it's apparently the "official" ISO currency code that no one uses but them. For that case, I created a separate currency enum that equality checks as equal to BTC. 

We'll deal with these issues on an exchange by exchange basis, either by manipulating the incoming data or by creating equalities between different currency codes. 

Most of them are standardized, so it's just the outliers like Kraken that are an issue.

**Comment by einsteinx2** [comment]
Done!
